name: Node CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          request_pty: true
          script: |
            cd umass-cics-community-bot
            git pull origin master
            bash -c "source ~/.bashrc && ./scripts/restart.sh"
